# Generated by Django 4.1.2 on 2022-10-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('nome_empresa', models.CharField(max_length=255)),
                ('responsavel', models.CharField(max_length=255)),
            ],
        ),
    ]
